name: Deploy to Deno Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Clean public directory
        run: |
          rm -rf public/*
          
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      # Downloads the frontend build (from frontend/web/build/) and places it in the public directory
      - name: Download Frontend Build
        uses: dawidd6/action-download-artifact@v2
        with:
          name: frontend-build
          path: public # This is where Deno serves static files from
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: recipe-app
          entrypoint: app.ts
          include: |
            app.ts
            deno.json
            import_map.json
            src/business/**/*
            src/data/**/*
            src/openapi/**/*
            src/presentation/**/*
            src/types/**/*
            src/utils/**/*
            public/**/*
