name: Deploy to Deno Deploy
on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Download Frontend Build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: public

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "recipe-app"
          entrypoint: "./app.ts"
          root: "."
          include: "public/,src/"
          exclude: "frontend/,android/,scripts/"
