name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27018:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: '2.1.4'  # Latest stable 2.x version

    - name: Make test script executable
      run: chmod +x test.sh
      
    - name: Run Tests
      env:
        MONGODB_URI: mongodb://127.0.0.1:27018/recipe_app_test
        MONGO_DB_NAME: recipe_app_test
      run: ./test.sh
